version: '3.8'

services:
  backend:
    build: ./backend
    container_name: mern-backend
    ports:
      - "8000:8000"
    environment:
      - PORT=8000
      - MONGO_URL=mongodb+srv://harsh:harsh@cluster0.oaeel.mongodb.net/jobPortal
    volumes:
      - ./backend:/app

  frontend:
    build: ./frontend
    container_name: mern-frontend
    ports:
      - "5173:80"
    depends_on:
      - backend
